### ISSUE TITLE
Is the source of the "base" seed available?

### ISSUE THREAD

**Issue by fnzr** [finger563/webgme-hfsm#128]
Hi,
I'd like to modify the meta attributes of the HSFM to fit with my own project, for example, adding a new Attribute to HSFM.State.
This is currently not possible because the HSFM meta is a Library, which prevents me from inheriting/modifying it. I know any changes are likely to break Simulation/Code generation, but that's ok.
Can you provide the original project for the HSFM library, please?

**Comment by finger563** [comment]
Hey fnzr,

This should be what you need (it's in the meta folder): https://github.com/finger563/webgme-hfsm/blob/master/src/meta/meta.webgmex

**Comment by finger563** [comment]
https://github.com/finger563/webgme-hfsm/wiki/How to integrate HFSM into your WebGME project

**Comment by fnzr** [comment]
I had found the seed file, but trying to import it (Create new project -> Import -> Import from file) fails with the error:
```
error: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close
error: [gme:server:standalone:middleware:BlobServer] Error: ReadStream was closed while writing file!
```

This is the server log. The client fails with a Internal Server Error exception. I tried both in the version of this repository, and in a clean install of the latest webgme. Same error.
Does importing works for you?

**Comment by kecso** [comment]
That is a known webgme issue. Known in the sense that there is a workaround and the upcoming release will solve it.
For the time being try to use this version of webgme https://github.com/webgme/webgme/releases/tag/v2.42.1-alpha.
(https://github.com/webgme/webgme-engine/issues/243)

**Comment by fnzr** [comment]
@kecso I see. Getting the release of webgme@2.42.1-alpha wasnt enough though, the error persisted. I had to pull the master branch of webgme-engine and use it instead of v2.25.2-alpha. Now the upload works, thanks.

@finger563 That's exactly what I was looking for, thank you!
