### ISSUE TITLE
Confusion about events, and possible payloads

### ISSUE THREAD

**Issue by digiexchris** [finger563/webgme-hfsm#160]
I'm having a little trouble wrapping my head around how events are used in the visualizer and code editor. If I needed an event with a payload, for example passing a value that needs to be used by the next state, how could I accomplish that? I see that transitions can have actions, but I'm not sure how to get the event to hold something that the state can then read. 

I likely am completely misunderstanding UML state machines, so please forgive me for the rookie question, and thanks in advance for your patience.

**Comment by finger563** [comment]
@digiexchris thanks for looking into webhme-hfsm! I hope you found the info you needed in how to pass data with events. I'm sorry the documentation isn't fully up to date, I should go through and update it sometime 😅

**Comment by digiexchris** [comment]
I did, thank you! I had to play with it a bit, I saw that after generating the code, there are event data objects I can add things to.
