### ISSUE TITLE
Create a context menu for moving a set of states and their transitions into another state

### ISSUE THREAD

**Issue by DWatkins** [finger563/webgme-hfsm#29]
![image](https://user-images.githubusercontent.com/455381/28138240-afd4550c-6715-11e7-85ca-8afa182bd0fa.png)

There is currently no easy way (from within the hfsmViz) to move states into another state as its children. For the example above, I cannot easily move `Standby` and `Active` into `No_Error`

**Comment by finger563** [comment]
For now: use the regular webgme model editor to select a group of objects and drag them into the model editor panel for the object that you want them to be children of (at which point you can select move, copy, instance).

future: apply same functionality to HFSM-viz

**Comment by DWatkins** [comment]
A somewhat more manageable feature would be to allow a single state to be dragged into another state and update any transitions into that state.

Example, click and drag from this:

![image](https://user-images.githubusercontent.com/455381/28183091-d14b477c-67d3-11e7-9721-73e300b5ccb9.png)

to this

![image](https://user-images.githubusercontent.com/455381/28183110-dec1fdb0-67d3-11e7-9bb9-86ac5ecc9bb0.png)

**Comment by finger563** [comment]
Will try to implement using this built-in library: https://github.com/webgme/webgme/blob/master/src/client/js/Controls/ContextMenu.js

with an example of use here:
https://github.com/webgme/webgme/blob/master/src/client/js/Widgets/DiagramDesigner/DiagramDesignerWidget.ContextMenu.js

Most likely will follow current webGME semantics where regular drag/drop moves the node in the viz, and then ctrl+drag and alt+drag and shift+drag provide the ability to copy, instance, and reparent respectively.  Will also add this context menu to the drag/drop actions from outside the viz to enable the same type of functionality.
