### ISSUE TITLE
Basic Development Process for complex HFSMs

### ISSUE THREAD

**Issue by DWatkins** [finger563/webgme-hfsm#31]
Develop the entire hfsm hierarchy as a roadmap before implementing `well-formed` sub-hfsms.  

Use the `Selected State` window in the hfsmViz to determine what states have been fully developed. Untouched states will display red for entry/exit. If a field is intentionally blank, add a space.

Define states from the top down and transitions from the bottom up.  

With no transitions defined into a state, it is impossible to reach that state, meaning it can be developed/compiled without affecting the behavior of the working portion of the hsfm.

**Comment by DWatkins** [comment]
a new attribute has been added to states called `isComplete` that changes the visualization in HSFMViz in order to be organize which states have been completed.

**Comment by finger563** [comment]
Please write this up a little more and add to the README under a new section: getting started

**Comment by finger563** [comment]
Probably include basic usage information into the README, e.g. how to create a project, an HFSM, and what the basic operations are:
* dragging / dropping objects from part browser
* dragging / drawing edges
* selecting objects for editing

Probably a good idea to make gifs for each of these to save on the amount of text that needs to be written / read

**Comment by DWatkins** [comment]
Include basic description of all objects and how to use them in webgme/viz

**Comment by finger563** [comment]
also should include #44 when it's ready

**Comment by finger563** [comment]
related to #67

**Comment by finger563** [comment]
have started a page on `Basic Development Process` on the wiki for this and have fleshed it out some (as well as updated the gifs and videos).
