### ISSUE TITLE
in HSFMViz, prevent states that are not children of another state from entering the bounds of that state 

### ISSUE THREAD

**Issue by DWatkins** [finger563/webgme-hfsm#33]
![image](https://user-images.githubusercontent.com/455381/28176107-d09ffc40-67bb-11e7-9545-6db59e91db5c.png)
 

Visually it looks that `Error` is a child of `Operational` along with the other states, instead of being a child of `HighLevelController` as shown below.

![image](https://user-images.githubusercontent.com/455381/28176203-279b8fc8-67bc-11e7-98b2-b4a42630000c.png)

**Comment by finger563** [comment]
Currently cannot enforce this as it is within the realm of cytoscape.js
