### ISSUE TITLE
Add support for local transitions

### ISSUE THREAD

**Issue by finger563** [finger563/webgme-hfsm#35]
Currently we only support External transitions (due to the rendering limitations of cytoscape.js, see https://github.com/cytoscape/cytoscape.js/issues/1897 )

Once that issue is resolved, update the meta and generators to support local transitions.

![uml_state_machine_fig8](https://user-images.githubusercontent.com/213467/28186744-f08a476a-67e1-11e7-9378-8d8360e8b6d8.png)

**Comment by finger563** [comment]
Note the convention:

_The local transition does not cause exit from the source, while the external transition causes exit and reentry to the source. In the bottom row of Figure 8, you see the case of the main target containing the main source. The local transition does not cause entry to the target, whereas the external transition causes exit and reentry to the target_

**Comment by finger563** [comment]
For now we can add this by coloring edges and supporting the better rendering when cytoscape adds support.

**Comment by finger563** [comment]
Need to update:
* meta
* generators

**Comment by finger563** [comment]
How to enable support for `cytoscape-edgehandles` to drag-drop and then select type of edge to create? or should we just have the local/external be a selection attribute in the transition?

**Comment by finger563** [comment]
Can easily repurpose the `Choice` modal dialog to pop up when dragging is complete to ask what kind of edge to create.

**Comment by finger563** [comment]
Should we enforce that all transition *pathways* will always be rendered as `External Transitions` since the pseudo-states may reside in different parts of the tree?

**Comment by DWatkins** [comment]
with the current implementation of pseudo-states this is probably a good approach.

**Comment by finger563** [comment]
For now I'm going to only allow Local Transitions when the src / dst are explicitly in a parent-child relationship - following the strict interpretation of the description above
