### ISSUE TITLE
Simulator does not work if initial state points towards a choice state

### ISSUE THREAD

**Issue by DWatkins** [finger563/webgme-hfsm#71]
Guard condition is never prompted and so a choice is never made.

**Comment by finger563** [comment]
will need to update generators so that `getInitial()` handles the case that the initial state's external transition points to choice state.

Similar issues would arise when initial points to another pseudo state (e.g. `End`, `Deep History`, `Shallow History`), but those would be mal-formed models.

**Comment by finger563** [comment]
will need to re-work the code to actually evaluate the conditionals required - right now the generator just returns the final pointer to the initial state without generating tree traversal code for getting it.

**Comment by finger563** [comment]
for generation, `getInitial` just needs to add extra handling code to recurse through all possible choice states.
